apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 767397734560.dkr.ecr.us-east-1.amazonaws.com/terra-project:latest

        ports:
        - containerPort: 80
